[tool.ruff]
    extend = "/presets/ruff.toml"

    [tool.ruff.isort]
        lines-after-imports = 2
        lines-between-types = 0
        section-order = ["future", "standard-library", "django", "third-party", "first-party", "project", "local-folder"]

    [tool.ruff.isort.sections]
        django = ["django"]
        project = ["divio_media_redirect"]
